[env:LoRaWan_Sensor01]
platform = heltec-cubecell
framework = arduino
board = cubecell_board

monitor_speed = 115200
monitor_port = /dev/ttyUSB0
upload_port = /dev/ttyUSB0

lib_deps =
  paulstoffregen/OneWire
  milesburton/DallasTemperature
  adafruit/DHT sensor library

; Projekt-Variablen zentral in platformio.ini
build_flags =
  -D LORA_DEV_EUI=0x03,0x8f,0x3e,0x1d,0x7e,0x59,0x71,0x70
  -D LORA_APP_EUI=0x40,0x61,0xc1,0xa6,0x85,0xea,0x7d,0x78
  -D LORA_APP_KEY=0xeb,0x93,0x01,0x9d,0x68,0xa3,0xfb,0x47,0x2d,0xa9,0x43,0x0b,0x18,0xc8,0x96,0xf4
  -D LORA_NWK_S_KEY=0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
  -D LORA_APP_S_KEY=0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
  -D LORA_DEV_ADDR=0x00000000
  -D LORA_KEEP_NET=0
  -D CFG_TX_DUTY_MS=900000
  -D CFG_APP_PORT=2
  -D CFG_CONFIRMED_TRIALS=4
  -D PIN_SENSOR1=GPIO3
  -D PIN_SENSOR2=GPIO2
  -D PIN_SENSOR3=GPIO1
  -D PIN_SENSOR4=GPIO5
  -D PIN_SENSOR5=GPIO0
  -D SENSOR1_TYPE=SENSOR_TYPE_REED
  -D SENSOR2_TYPE=SENSOR_TYPE_REED
  -D SENSOR3_TYPE=SENSOR_TYPE_REED
  -D SENSOR4_TYPE=SENSOR_TYPE_DS18B20
  -D SENSOR5_TYPE=SENSOR_TYPE_DHT22
  -D PIN_IMMEDIATE_TX=GPIO7
  -D REED_DEBOUNCE_MS=80
  -D REED_EVENT_COOLDOWN_MS=30000

; LoRaWAN Build-Optionen (anpassen bei Bedarf)
board_build.arduino.lorawan.region = EU868
board_build.arduino.lorawan.class = CLASS_A
board_build.arduino.lorawan.netmode = OTAA
board_build.arduino.lorawan.adr = ON
board_build.arduino.lorawan.uplinkmode = UNCONFIRMED
board_build.arduino.lorawan.debug_level = NONE
